### ISSUE TITLE
Incompatible with Zotero 6.x

### ISSUE THREAD

**Issue by salim-b** [lanl/Zotero-Robust-Links-Extension#2]
![Bildschirmfoto von 2022-04-08 02-34-55](https://user-images.githubusercontent.com/20040931/162340768-050c7b04-f912-4d76-9b95-93a6b2cd6833.png)

**Comment by shawnmjones** [comment]
Thanks for the issue @salim-b! We recently updated our code to support Zotero 6.

From where did you download the XPI file?

I ask because we have several download locations and I fear they have gotten out of sync.

**Comment by salim-b** [comment]
> From where did you download the XPI file?

From [GitHub releases](https://github.com/lanl/Zotero-Robust-Links-Extension/releases). I guess once an add-on is disabled, it doesn't auto-update anymore?

Anyways, thanks for the new release! Had to install it manually, but seems to work fine with latest Zotero.

**Comment by shawnmjones** [comment]
I found the problem. We released a new XPI on [our web site](https://robustlinks.mementoweb.org/zotero/) but we failed to update the GitHub repository and make sure everything was using the same XPI URL.

Try it now. We are working on getting auto-update working for this extension. :-)

**Comment by salim-b** [comment]
> Try it now. We are working on getting auto-update working for this extension. :-)

I have installed the [latest release from GitHub](https://github.com/lanl/Zotero-Robust-Links-Extension/releases/tag/v2.0.0-20220320145937). Is that what you want me to try?

I don't know how I could test whether auto-update works since now I obviously got the latest version already...
